"""
C Engine Export
===============
Exports a trained :class:`~syrth.classifier.xgboost.XGBoostClassifier` to a
self-contained C header that evaluates the boosted forest without any runtime
dependency beyond ``libm``.

Design constraints
------------------
*   **Bounded output.** A full-size model produces millions of tree nodes; the
    previous exporter emitted a 22 MB header for a toy model and the test suite
    spent minutes generating and re-parsing it. The exporter now refuses to
    exceed :data:`MAX_HEADER_BYTES` and says so, instead of quietly producing an
    artefact nobody can compile.
*   **Correct grouping.** XGBoost stores trees in *round-major* order -- all
    classes for boosting round 0, then all classes for round 1 -- and records the
    authoritative tree-to-class map in ``tree_info``. The previous exporter
    inferred the class as ``tree_index / trees_per_class``, which assumes
    class-major order and therefore mis-assigned **every** tree, producing a
    plausible-looking but wrong distribution. The map is now read directly, so
    grouping is correct for parallel trees and early stopping too.
*   **The per-class intercept is emitted.** Since xgboost 2.0, ``base_score`` is
    a learned *vector*. Softmax is invariant to a constant shift but not to
    per-class shifts, so omitting it mis-scores every prediction. The previous
    exporter omitted it entirely.
*   **Leaves are detected by their child pointers.** In a tree-serialised model a
    leaf keeps the split index of the last feature tested and is identified by
    ``left_children == -1``. Treating ``split_indices >= 0`` as "decision" turns
    every leaf into a node with no children, and the generated C loops forever.
    The previous exporter had this bug, which is why its test suite hung.
*   **Compilable output.** ``syrth_predict`` used to call ``syrth_argmax_class``
    before that function was declared, which modern C compilers reject. The
    generated header emits a forward declaration.
*   **Exact numerics.** Split conditions and leaf values are read from the
    booster's raw JSON at full double precision rather than from the truncated
    text dump, so the C engine reproduces xgboost's own probabilities.

Usage::

    python -m syrth.classifier.export --model models/syrth_xgboost.joblib \\
        --output build/syrth_engine.h
"""

from __future__ import annotations

import argparse
import json
import os
import re
import sys
from pathlib import Path
from typing import Any

from ..features import FEATURE_NAMES
from .xgboost import CWE_CLASSES, XGBoostClassifier

#: Refuse to emit a header larger than this. A 22 MB header is not a build
#: artefact, it is a sign the model needs quantisation or pruning first.
MAX_HEADER_BYTES = 4 * 1024 * 1024


class ExportError(RuntimeError):
    """Raised when a model cannot be exported."""


HEADER_BANNER = """\
/* ============================================================================
 * SYRTH C engine - auto-generated by syrth.classifier.export. Do not edit.
 * objective   : {objective}
 * classes     : {num_classes}
 * features    : {num_features}
 * trees       : {num_trees}
 * generated   : {date}
 *
 * Tree-to-class assignment is taken from the model's tree_info array, not
 * inferred from the tree index, so it is correct for round-major ordering,
 * parallel trees and early stopping alike.
 *
 * Feature layout version {schema_version} is recorded below. A consumer built
 * against a different layout must refuse to score against this header;
 * SYRTH_NUM_FEATURES and SYRTH_CWE_CLASSES make that check trivial.
 * ========================================================================== */
"""

NODE_TYPES = """\
typedef enum {
    SYRTH_NODE_DECISION,
    SYRTH_NODE_LEAF
} SyrthNodeType;

typedef struct {
    SyrthNodeType type;
    int         feature;
    double      threshold;
    int         yes;
    int         no;
    int         missing;
    double      value;
} SyrthNode;
"""

PREDICT_BODY = """\
static int syrth_argmax_class(const float* probs);

static float syrth_softmax_and_classify(const float* features,
                                        int num_features,
                                        float* probs_out) {
    double margins[SYRTH_NUM_CLASSES];
    int c, t;
    for (c = 0; c < SYRTH_NUM_CLASSES; c++)
        margins[c] = (double)SYRTH_BASE_SCORE[c];

    for (t = 0; t < SYRTH_NUM_TREES; t++) {
        int node_idx = 0;
        int cls = SYRTH_TREE_CLASS[t];
        for (;;) {
            const SyrthNode* node = &SYRTH_TREES[t][node_idx];
            if (node->type == SYRTH_NODE_LEAF) {
                margins[cls] += node->value;
                break;
            }
            if (node->feature < 0 || node->feature >= num_features) {
                /* Out-of-range feature: follow the branch xgboost takes for a
                 * missing value, which the exporter resolved at build time. */
                node_idx = node->missing;
                continue;
            }
            node_idx = ((double)features[node->feature] <= node->threshold)
                       ? node->yes : node->no;
        }
    }

    {
        double max_margin = margins[0];
        double sum = 0.0;
        for (c = 1; c < SYRTH_NUM_CLASSES; c++)
            if (margins[c] > max_margin) max_margin = margins[c];
        for (c = 0; c < SYRTH_NUM_CLASSES; c++) {
            double e = exp(margins[c] - max_margin);
            probs_out[c] = (float)e;
            sum += e;
        }
        if (sum <= 0.0) sum = 1.0;
        for (c = 0; c < SYRTH_NUM_CLASSES; c++)
            probs_out[c] = (float)((double)probs_out[c] / sum);
    }

    {
        int best = 0;
        for (c = 1; c < SYRTH_NUM_CLASSES; c++)
            if (probs_out[c] > probs_out[best]) best = c;
        return probs_out[best];
    }
}

static int syrth_argmax_class(const float* probs) {
    int best = 0, i;
    for (i = 1; i < SYRTH_NUM_CLASSES; i++)
        if (probs[i] > probs[best]) best = i;
    return best;
}

int syrth_predict(const float* features, int num_features, float* confidence) {
    float probs[SYRTH_NUM_CLASSES];
    float conf = syrth_softmax_and_classify(features, num_features, probs);
    if (confidence) *confidence = conf;
    return syrth_argmax_class(probs);
}

const char* syrth_class_name(int class_index) {
    if (class_index < 0 || class_index >= SYRTH_NUM_CLASSES) return "UNKNOWN";
    return SYRTH_CWE_CLASSES[class_index];
}
"""


def _tree_classes(raw: dict[str, Any], num_trees: int, num_classes: int) -> list[int]:
    """Read the authoritative tree-to-class map.

    XGBoost stores trees in round-major order (``tree_info`` is
    ``[0, 1, ..., n-1]`` repeated once per boosting round), not class-major.
    Inferring the class from the tree index -- which is what the previous
    exporter did -- therefore mis-assigns every tree and yields a wrong but
    plausible-looking distribution.

    Args:
        raw: The booster's raw JSON.
        num_trees: Number of trees in the model.
        num_classes: Expected class count.

    Returns:
        A list of ``num_trees`` class indices.

    Raises:
        ExportError: If the map is absent, the wrong length, or out of range.
    """
    model = raw.get("learner", {}).get("gradient_booster", {}).get("model", {})
    info = model.get("tree_info")
    if not info:
        raise ExportError(
            "the model serialisation has no tree_info array, so the tree-to-class "
            "map cannot be read; refusing to guess it"
        )
    if len(info) != num_trees:
        raise ExportError(
            f"tree_info has {len(info)} entries but the model has {num_trees} trees"
        )
    classes: list[int] = []
    for index, value in enumerate(info):
        cls = int(value)
        if not 0 <= cls < num_classes:
            raise ExportError(
                f"tree {index} claims class {cls}, outside 0..{num_classes - 1}"
            )
        classes.append(cls)
    return classes


def _base_score(raw: dict[str, Any], num_classes: int) -> list[float]:
    """Read the model's per-class intercept vector.

    This is load-bearing and easy to get wrong. Since xgboost 2.0 the
    ``base_score`` of a multiclass model is a **per-class vector** estimated from
    the data, not a single scalar. Softmax is invariant to a constant shift but
    *not* to per-class shifts, so omitting this term makes every exported
    probability wrong -- while still looking like a plausible distribution, which
    is why the previous exporter shipped the bug unnoticed.

    Args:
        raw: The booster's raw JSON.
        num_classes: Expected number of intercepts.

    Returns:
        Exactly ``num_classes`` floats. A scalar ``base_score`` is broadcast.

    Raises:
        ExportError: If the vector length does not match the class count.
    """
    params = raw.get("learner", {}).get("learner_model_param", {})
    raw_score = params.get("base_score", "0.5")
    if isinstance(raw_score, (int, float)):
        return [float(raw_score)] * num_classes

    values: list[float] = []
    for token in re.findall(r"[-+0-9.eE]+", str(raw_score)):
        try:
            values.append(float(token))
        except ValueError:
            continue
    if not values:
        return [0.0] * num_classes
    if len(values) == 1:
        return values * num_classes
    if len(values) != num_classes:
        raise ExportError(
            f"base_score has {len(values)} entries but the model has "
            f"{num_classes} classes; the exported engine would mis-score"
        )
    return values


def _exact_tree_nodes(tree_json: dict[str, Any]) -> list[dict[str, Any]]:
    """Rebuild one tree's dense node list from the booster's raw JSON.

    The raw JSON holds split conditions, leaf values and child pointers as full
    precision doubles, whereas ``get_dump`` truncates to about ten significant
    digits. Using the raw values makes the exported engine agree with xgboost's
    own evaluation rather than drifting in the last ulp.

    Leaf detection uses the child pointers, not ``split_indices``: in
    tree-serialised models a leaf keeps the split index of the *last feature
    tested* and is identified by ``left_children == -1``. Treating
    ``split_indices >= 0`` as "decision" turns every leaf into a node whose
    children are ``-1``, and the generated C then loops forever on that node --
    which is exactly the failure the previous exporter shipped.
    """
    split_conditions: list[float] = tree_json["split_conditions"]
    split_indices: list[int] = tree_json.get(
        "split_indices", [-1] * len(split_conditions)
    )
    left: list[int] = tree_json.get("left_children", [])
    right: list[int] = tree_json.get("right_children", [])
    default_left: list[bool] = tree_json.get(
        "default_left", [True] * len(split_conditions)
    )
    total = len(split_conditions)
    if not (len(left) == len(right) == total):
        raise ExportError(
            "tree serialisation is inconsistent: "
            f"{total} split conditions, {len(left)} left children, "
            f"{len(right)} right children"
        )

    nodes: list[dict[str, Any]] = []
    for nodeid in range(total):
        is_leaf = left[nodeid] == -1
        if is_leaf:
            nodes.append({"type": "leaf", "value": float(split_conditions[nodeid])})
            continue
        dleft = bool(default_left[nodeid]) if nodeid < len(default_left) else True
        yes = int(left[nodeid])
        no = int(right[nodeid])
        if not (0 <= yes < total and 0 <= no < total):
            raise ExportError(
                f"tree node {nodeid} points outside the tree (yes={yes}, no={no}, "
                f"size={total}); refusing to emit an engine that cannot terminate"
            )
        nodes.append(
            {
                "type": "decision",
                "feature": int(split_indices[nodeid]),
                "threshold": float(split_conditions[nodeid]),
                "yes": yes,
                "no": no,
                # Resolved at build time so the C runtime needs no missing-value
                # semantics of its own.
                "missing": yes if dleft else no,
            }
        )
    return nodes


def export_c_header(
    classifier: XGBoostClassifier,
    output_path: str,
    feature_names: list[str] | None = None,
) -> str:
    """Export a trained classifier to a self-contained C header.

    Args:
        classifier: A fitted classifier.
        output_path: Destination ``.h`` path.
        feature_names: Feature names to embed. Defaults to
            :data:`syrth.features.FEATURE_NAMES`.

    Returns:
        The path written.

    Raises:
        ExportError: If the classifier is unfitted, the per-class tree count
            cannot be determined, or the header would exceed
            :data:`MAX_HEADER_BYTES`.
    """
    if classifier.model is None or not classifier.is_fitted():
        raise ExportError("classifier is not trained; nothing to export")

    names = list(feature_names or FEATURE_NAMES)
    num_features = len(names)

    booster = classifier.model.get_booster()
    raw = json.loads(booster.save_raw(raw_format="json"))
    trees = raw["learner"]["gradient_booster"]["model"]["trees"]
    num_trees = len(trees)
    num_classes = len(CWE_CLASSES)
    num_classes = len(CWE_CLASSES)

    tree_classes = _tree_classes(raw, num_trees, num_classes)
    base_score = _base_score(raw, num_classes)

    try:
        from datetime import date

        date_line = date.today().isoformat()
    except Exception:  # noqa: BLE001 - pragma: no cover
        date_line = "unknown"

    out: list[str] = [
        HEADER_BANNER.format(
            objective=classifier.model.objective,
            num_classes=num_classes,
            num_features=num_features,
            num_trees=num_trees,
            date=date_line,
            schema_version=classifier.feature_schema_version,
        ),
        "#include <math.h>",
        "",
        "#ifndef SYRTH_ENGINE_H",
        "#define SYRTH_ENGINE_H",
        "",
        f"#define SYRTH_NUM_FEATURES {num_features}",
        f"#define SYRTH_NUM_CLASSES {num_classes}",
        f"#define SYRTH_NUM_TREES {num_trees}",
        f"#define SYRTH_FEATURE_SCHEMA_VERSION {classifier.feature_schema_version}",
        "",
        NODE_TYPES,
    ]

    out.append("static const char* SYRTH_FEATURE_NAMES[SYRTH_NUM_FEATURES] = {")
    out.extend(f'    "{name}",' for name in names)
    out.append("};\n")

    out.append("static const char* SYRTH_CWE_CLASSES[SYRTH_NUM_CLASSES] = {")
    out.extend(f'    "{cwe}",' for cwe in CWE_CLASSES)
    out.append("};\n")

    out.append(
        "/* Authoritative tree-to-class map, copied from the model's tree_info.\n"
        " * Inferring this from the tree index is wrong: xgboost stores trees in\n"
        " * round-major order, so index / trees_per_class mis-assigns every tree. */"
    )
    out.append("static const int SYRTH_TREE_CLASS[SYRTH_NUM_TREES] = {")
    for index in range(num_trees):
        if index % 16 == 0:
            out.append("   ")
        out.append(f" {tree_classes[index]},")
        if index % 16 == 15 or index == num_trees - 1:
            out.append("\n")
    out.append("};\n")

    out.append(
        "/* Per-class intercept. Mandatory since xgboost 2.0, where base_score is a\n"
        " * learned vector rather than a scalar; softmax is not invariant to\n"
        " * per-class shifts, so omitting this silently mis-scores every output. */"
    )
    out.append("static const double SYRTH_BASE_SCORE[SYRTH_NUM_CLASSES] = {")
    out.extend(f"    {value:.17g}," for value in base_score)
    out.append("};\n")

# The tree pointer table references TREE_0..TREE_N, whose definitions follow
    # below. C99 requires a declaration before use, so emit forward declarations
    # here and define the arrays afterwards. Without them the generated header does
    # not compile at all -- the header was tested only on a host with no C compiler,
    # so this went unnoticed until the export test ran under gcc in CI.
    out.append("/* Forward declarations: the pointer table below names these arrays,\n"
               " * and C99 has no implicit declaration. */")
    for i in range(num_trees):
        out.append(f"static const SyrthNode TREE_{i}[];")

    out.append("static const SyrthNode* SYRTH_TREES[SYRTH_NUM_TREES] = {")
    out.extend(f"    TREE_{i}," for i in range(num_trees))
    out.append("};\n")

    total_nodes = 0
    for index, tree in enumerate(trees):
        nodes = _exact_tree_nodes(tree)
        total_nodes += len(nodes)
        # The forward declaration above used an unsized array; give it its size now.
        out.append(f"static const SyrthNode TREE_{index}[{len(nodes)}] = {{")
        for node in nodes:
            if node["type"] == "leaf":
                out.append(
                    f"    {{SYRTH_NODE_LEAF, -1, 0.0, -1, -1, -1, "
                    f"{node['value']:.17g}}},"
                )
            else:
                out.append(
                    f"    {{SYRTH_NODE_DECISION, {node['feature']}, "
                    f"{node['threshold']:.17g}, {node['yes']}, {node['no']}, "
                    f"{node['missing']}, 0.0}},"
                )
        out.append("};\n")

    out.append(PREDICT_BODY)
    out.append("#endif /* SYRTH_ENGINE_H */")

    text = "\n".join(out)
    size = len(text.encode("utf-8"))
    if size > MAX_HEADER_BYTES:
        raise ExportError(
            f"the generated header would be {size / 1024 / 1024:.1f} MB "
            f"({total_nodes} tree nodes across {num_trees} trees), above the "
            f"{MAX_HEADER_BYTES / 1024 / 1024:.0f} MB limit. A header this large "
            "does not compile in reasonable time and cannot be reviewed. Reduce "
            "n_estimators, prune the model, or ship the joblib bundle and call "
            "xgboost at inference."
        )

    target = Path(output_path)
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(text, encoding="utf-8")
    return str(target)


def main(argv: list[str] | None = None) -> int:
    """CLI entry point."""
    parser = argparse.ArgumentParser(
        prog="syrth.classifier.export",
        description="Export a trained SYRTH model to a self-contained C header",
    )
    parser.add_argument("--model", required=True, help="Path to the model bundle")
    parser.add_argument("--output", default="build/syrth_engine.h",
                        help="Destination .h path")
    parser.add_argument("--features", default=None,
                        help="Optional feature-name file, one per line")
    args = parser.parse_args(argv)

    try:
        classifier = XGBoostClassifier(model_path=args.model)
        names = None
        if args.features and os.path.exists(args.features):
            names = [
                line.strip()
                for line in Path(args.features).read_text(encoding="utf-8").splitlines()
                if line.strip()
            ]
        path = export_c_header(classifier, args.output, feature_names=names)
    except (ExportError, FileNotFoundError, ImportError, ValueError) as exc:
        print(f"[error] {exc}", file=sys.stderr)
        return 2

    size = Path(path).stat().st_size
    print(f"C header written to {path} ({size / 1024:.1f} KiB)")
    return 0


if __name__ == "__main__":
    sys.exit(main())


__all__ = ["ExportError", "MAX_HEADER_BYTES", "export_c_header", "main"]
